### ISSUE TITLE
New components `<Head>` and `<Config>`

### ISSUE THREAD

**Issue by brillout** [vikejs/vike-solid#105]
`vike-solid` now has [a `useConfig()` component hook](https://vike.dev/useConfig) (see PR #102).

The only thing missing to align with `vike-react` is to implement [the `<Config>` and `<Head>` components](https://vike.dev/useConfig#config-head).

My failed attempt to implement it: https://github.com/vikejs/vike-solid/pull/104.

Contribution welcome.

**Comment by phonzammi** [comment]
Does the `<Head>` component need to be hydrated?

**Comment by brillout** [comment]
It doesn’t: it’s only used for HTML

**Comment by phonzammi** [comment]
We can wrap it with solidjs's `<NoHydration>` component

**Comment by brillout** [comment]
Neat, although it's the user who would nead to do the wrapping right?

**Comment by phonzammi** [comment]
Another workaround is using solidjs's `<Show>` component like this:
```jsx
<Show when={isServer}>
  <Head>
    <script
      type="application/ld+json"
      innerHTML={JSON.stringify({
        "@context": "https://schema.org/",
        contentUrl: { src },
        creator: {
          "@type": "Person",
          name: author,
        },
      })}
    ></script>
  </Head>
</Show>
```

**Comment by brillout** [comment]
> it’s a bit of a bummer

Indeed, but better than no solution at all though.

**Comment by brillout** [comment]
I wonder if `<Show when={import.meta.env.SSR}>` would enable code elimination.

**Comment by phonzammi** [comment]
`<Show when={import.meta.env.SSR}>` also works

**Comment by brillout** [comment]
> `<Show when={import.meta.env.SSR}>` also works

[Indeed](https://github.com/vikejs/vike-solid/pull/104/commits/3d01dc7001c1fd2ef9b364a509966cbf1b04a00a).

Although it doesn't seem to remove `<Head>` on the client-side:

![image](https://github.com/user-attachments/assets/ff52e8f6-aaf7-4e43-bc1d-84b44214e2c7)

**Comment by brillout** [comment]
Let's see what Ryan says :eyes: https://github.com/solidjs/solid/issues/2248#issuecomment-2276465278

**Comment by brillout** [comment]
Done: https://github.com/vikejs/vike-solid/issues/105.

@phonzammi FYI [this did the trick](https://github.com/solidjs/solid/issues/2248#issuecomment-2277567250).

**Comment by phonzammi** [comment]
Neat trick :100:
