### ISSUE TITLE
Missing transitive `vite` peer dependency

### ISSUE THREAD

**Issue by rtritto** [vikejs/vike-solid#110]
`vite-plugin-solid` has `vite` as peer dependency.
`vike` use `vite-plugin-solid` dependency and it should also include `vite` as peer dependency.

```console
yarn explain peer-requirements
...
p26fd0 → ✘ vike-solid@npm:0.7.3 [839d2] doesn't provide vite to vite-plugin-solid@npm:2.10.2 [e76e3] and 1 other dependency
...
```

**Comment by brillout** [comment]
Fix pre-released as `0.7.3-commit-704e0a7`.
