### ISSUE TITLE
No hydration with `useData` hook and routing param on page change

### ISSUE THREAD

**Issue by rtritto** [vikejs/vike-solid#114]
## Description

With route `/pages/@name`, on navigate with `a` component, the url is correctly update but the page isn't rendered with new content.

Before the commit [d82c216](https://github.com/rtritto/template-vike-solid-daisyui/commit/d82c2169b4becb0145722de8c5c02779b7f8a0e3), it correctly works with both routes (`/pages/product` and `/pages/item`)

Behaviour of the example: navigate on first page and click on link to navigate on second page; then click to link to come back to the first page

## Reproduction
1. `git clone https://github.com/rtritto/template-vike-solid-daisyui.git`
2. `cd template-vike-solid-daisyui`
3. `git checkout bug-render-link`
4. `yarn`
5. `yarn dev`
6. Navigate to `http://localhost:3000/product`
7. Click on _Link_ to navigate on `http://localhost:3000/item`
8. Only the url path is update to `http://localhost:3000/item` but the page isn't updated/hydrated (the _href_ attribute of the `a` component isn't updated to `http://localhost:3000/product`)

**Comment by magne4000** [comment]
Fixed in `0.7.4`. You should update your code to avoid destructuring `useData`:

```
const data = useData<Data>()
return <a href={`/${data.nextPage}`}>Link to {data.nextPage}</a>
```
