### ISSUE TITLE
[vike-solid] `useRouter` hook

### ISSUE THREAD

**Issue by rtritto** [vikejs/vike-solid#120]
Add the `useRouter` hook like [useRouter](https://nextjs.org/docs/pages/api-reference/functions/use-router) of Next.js

**Comment by brillout** [comment]
What's the benefit of `userRouter()` over `pageContext.urlParsed` and `navigate()`? Closing but let's continue the conversation and re-open if it's a valid feature request.

**Comment by rtritto** [comment]
My use case with Next.js:
```ts
router.push(<URL>, undefined, { shallow: true })
```
Same in Vike:
```ts
window.history.pushState(null, '', <URL>)
```

Alternative:
```ts
window.history.replaceState(null, '', <URL>)
```
---
The `useRouter` hook like [useRouter](https://nextjs.org/docs/pages/api-reference/functions/use-router) of Next.js isn't needed
