### ISSUE TITLE
Upgrading from 0.7.6 to 0.7.7 breaks Nested/Cumulative Layouts.

### ISSUE THREAD

**Issue by Blankeos** [vikejs/vike-solid#144]
After upgrading from `0.7.6` to `0.7.7`, layouts seem to be breaking.

<img width="1001" alt="image" src="https://github.com/user-attachments/assets/11cf4827-5572-4317-8679-c6729681c4ca" />

I tried...
✅ `vike-solid@0.7.6` and `vike@0.4.210`. It works. (using `vite@5.4.11`)
❌ `vike-solid@0.7.7` and `vike@0.4.210`. It doesn't work. (using `vite@5.4.11`)
❌ `vike-solid@0.7.7` and `vike@0.4.206`. It doesn't work. (using `vite@5.4.11`)

I also thought maybe it was just Vite, but no. Because:
❌ `vike-solid@0.7.7` and `vike@0.4.210`. It doesn't work. (using `vite@6.0.3`)
✅ `vike-solid@0.7.6` and `vike@0.4.210`. It works. (using `vite@6.0.3`)

So I kinda conclude It's because of vike-solid@0.7.7.

Still investigating what the cause is... So opening this issue for that.
I'm trying to compare the changes from 0.7.6 to 0.7.7: https://github.com/vikejs/vike-solid/compare/94bda74...16c9c82 (I just used the `release: 0.7.6` and `release: 0.7.7` commits).

## Reproduction

I will add here when I can, but you can maybe use my boilerplate: https://github.com/blankeos/solid-hop (It's pretty barebones). And then reproduce the package versions I mentioned above.

**Comment by Blankeos** [comment]
So I noticed, it only breaks for Nested Layouts, that's when it shows the `Maximum call stack size exceeded` error.

**Comment by brillout** [comment]
@rtritto @Blankeos Up for digging into this? It would be nice if the community can (eventually) take over `vike-solid` so that the Vike team can focus on other parts of Vike. There is also: https://github.com/vikejs/vike-solid/issues.

**Comment by Blankeos** [comment]
Yep looking into it. I'm getting somewhere:

<details>
<summary>Debugging Code</summary>

...
<img width="726" alt="image" src="https://github.com/user-attachments/assets/d92514e3-5da5-46ce-85a4-90295589c015" />

</details>
1. onMount

<img width="1127" alt="image" src="https://github.com/user-attachments/assets/47c1f058-f455-4fc0-93cb-19101a403493" />

2. on page navigations... (I found the infinite recursive call)

Notice how i is supposed to be a number, but it seems to be a signal?, essentially it's recursively calling `renderWrappers()` multiple times

<img width="1129" alt="image" src="https://github.com/user-attachments/assets/20da52eb-19d4-4cd4-9437-9296a22c0965" />


---

The fix is this. I actually have no idea why the 0 was removed. iirc, I added a 0 as a default here before, hence the call was just `renderWrappers()` [(Old commit where this was functional before)](https://github.com/Blankeos/vike-solid/blob/a73fd10b359771ae18b2e1d5b86bbdc9c5d0c5e9/vike-solid/renderer/getPageElement.tsx#L28C45-L29C1)
<img width="705" alt="image" src="https://github.com/user-attachments/assets/20237ab4-b1be-4e98-8225-282800856a9b" />

**Comment by Blankeos** [comment]
#### I discovered something really stupid with Javascript (or maybe Solid)

I noticed simply changing array indexing from `.at` to `[]`, and the state actually gets persisted?? 

Not sure what's so fundamentally different between them because I genuinely thought they were the same!! Just that `.at()` has the ability to index backwards (like `-1` as the last element).

So the fix on the second bug from https://github.com/vikejs/vike-solid/issues/144#issuecomment-2553847636. Is actually:
```ts
// Assuming you `.toReversed()` in the reconcile.
let item = wrappers.at(props.index) // ❌ bad
let item = wrappers[props.index] // ✅ good? 

// If we don't reverse and just access backwards...
let item = wrappers.at(-(i + 1)); // ❌ bad.
let item = wrappers[layouts.length - 1 - index] // ✅ good?
```

I bumped into this on a whim while fixing this bug.

**Comment by magne4000** [comment]
Interesting findings. It would probably be a good idea to check if such issues are already known by the Solid team, and open some issues if that is not the case.

**Comment by rtritto** [comment]
Opened 2 related issues:
- https://github.com/solidjs-community/eslint-plugin-solid/issues/174
- https://github.com/solidjs-community/eslint-plugin-solid/issues/175
