### ISSUE TITLE
usePageContext doesn't update Provider that wraps LayoutDefault, but should it?

### ISSUE THREAD

**Issue by nonamich** [vikejs/vike-solid#64]
👋🏼 Hello! First of all, thank you for a great plugin.

I'm not a big solid.js guy, so maybe I'm just missing something.

Reproduction: [codesandbox](https://codesandbox.io/p/github/nonamich/vike-solid-reproduction/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsz9pqnt0006356jn2dydc36%2522%252C%2522sizes%2522%253A%255B10%252C90%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsz9pqnt0002356jhslivwu3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsz9pqnt0004356j67stpp5x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsz9pqnt0005356j9kbmkm3z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsz9pqnt0002356jhslivwu3%2522%253A%257B%2522id%2522%253A%2522clsz9pqnt0002356jhslivwu3%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clszazeq2036w356j2tg2c48x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clszazeq2036w356j2tg2c48x%2522%257D%252C%2522clsz9pqnt0005356j9kbmkm3z%2522%253A%257B%2522id%2522%253A%2522clsz9pqnt0005356j9kbmkm3z%2522%252C%2522activeTabId%2522%253A%2522clsz9s22100l1356j0zzwxno0%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clsz9s22100l1356j0zzwxno0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clsz9pqnt0004356j67stpp5x%2522%253A%257B%2522id%2522%253A%2522clsz9pqnt0004356j67stpp5x%2522%252C%2522activeTabId%2522%253A%2522clsz9qw30009q356joje20z8r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsz9pqnt0003356j5ga9wxwx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clsz9pqzn0010degp29up11mu%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clsz9qv120056356jcyzac4oy%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clsz9qw30009q356joje20z8r%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Description of the reproduction: 
1. I added `onBeforeRender` which simply adds a string of random letters.
2. createContext which should store this string.
3. Context.Provider which is the first component in `LayoutDefault`.
4. The actual `useRandom` hook that will output this string of random letters.
5. I added 2 pages that have `useRandom` and `usePageContext`. useRandom always returns the string that was added at the first render. `usePageContext` returns the current data (in case it is called not in `Layout` but in `Page`). 
6. Two more pages (page-with-provider) that have the top component of the Provider itself, in this case it works well, but adding a Provider for each page does not.

Actually, in a real project, I use I18n instead of the stupid random string of letters. Some pages have their own [namespaces](https://www.i18next.com/principles/namespaces) that need to be loaded for each page separately to optimise response size.

**Comment by magne4000** [comment]
That indeed seems like unwanted behaviour, let me take a look at it. And thanks for the detailed reproduction!

**Comment by magne4000** [comment]
@nonamich In fact it's [documented](https://www.solidjs.com/docs/latest/api#createcontext):
> The value passed to provider is passed to useContext as is. That means wrapping as a reactive expression will not work. You should pass in Signals and Stores directly instead of accessing them in the JSX.

i.e. you have to pass a Signal or Store to the provider if you want it to be reactive
