### ISSUE TITLE
`ClientOnly` fallback triggers with nested unresolved resources

### ISSUE THREAD

**Issue by andriygm** [vikejs/vike-solid#72]
`ClientOnly` has a `Suspense` boundary, causing any unresolved resources within a `ClientOnly` to trigger it's own fallback. Instead, it should fallback specifically when the `ClientOnly` import itself is unresolved.

**Comment by magne4000** [comment]
`ClientOnly` component is now replaced by a [clientOnly](https://github.com/vikejs/vike-solid/pull/74) function, which [works the same as in solid-start](https://docs.solidjs.com/solid-start/reference/client/client-only). Published in `v0.4.3`
