### ISSUE TITLE
How to add <title> inside +Head instead of +config?

### ISSUE THREAD

**Issue by Blankeos** [vikejs/vike-solid#83]
It seems to not respect my +Head tag, I purposely choose not to put any title in +config. On first page load I get the title I want. But when I navigate on the clientside, I don't get the title tag anymore.

```tsx
// Default <head> (can be overridden by pages)

import { mergeProps, Show, VoidProps } from 'solid-js';

type DefaultHeadProps = {
  /** Replaces the %s with the title prop. */
  titleTemplate?: string;
  title?: string;
  description?: string;
  imageURL?: string;
};

export function DefaultHead(props: VoidProps<DefaultHeadProps>) {
  const _props = mergeProps(
    {
      title: 'Home',
      titleTemplate: '%s | Solid Launch',
      description: 'An awesome app template by Carlo Taleon.',
      imageURL: 'https://assets.solidjs.com/banner?type=SolidLaunch&background=tiles&project=%20'
    },
    props
  );

  return (
    <>
      <Show
        when={_props.titleTemplate}
        children={<title>{_props.titleTemplate!.replace('%s', _props.title!)}</title>}
        fallback={<title>{_props.title}</title>}
      />
      <meta name="description" content={_props.description} />
      <link rel="icon" href="/favicon.svg" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="og:image" content={_props.imageURL} />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:creator" content="@carlo_taleon" />
      <meta name="twitter:title" content="Solid Launch" />
      <meta name="twitter:description" content={_props.description} />
      <meta name="twitter:image" content={_props.imageURL} />
    </>
  );
}
```

On my pages I put:
```tsx
// about
import { DefaultHead } from '@/components/common/default-head';

export const Head = () => <DefaultHead title="About" />;
```

```tsx
// home
import { DefaultHead } from '@/components/common/default-head';

export const Head = () => <DefaultHead title="Home" />;
```

**Comment by brillout** [comment]
As for `titleTemplate`, it's actually on the radar for the upcoming revamped head management design.

**Comment by Blankeos** [comment]
@brillout Thanks for the quick response!  

> > I purposely choose not to put any title in +config
>
> Why is that?

So I can do dynamic title templates.

> As for titleTemplate, it's actually on the radar for the upcoming revamped head management design.

That's good to hear! Can't wait! 

But yeah, it's not needed to update the meta tags on client-side navigation but it looks kinda weird when I look at it here:
- Notice when I reload, the title shows. (other metas are fine, it's just the title).
- I think it's because I purposely don't put a title in +config so I get the blank title because +config takes precedence? Not sure.

https://github.com/vikejs/vike-solid/assets/38070918/678c5743-8edd-4112-ad39-d34139e1fb53

**Comment by brillout** [comment]
It's because of `|| ""` in the following line. https://github.com/vikejs/vike-solid/blob/b7f5abd19afb913b561e595fe466b4a68d8f7053/vike-solid/renderer/onRenderClient.tsx#L40

The idea is to clear the `<title>` set by the previous page. I think we can remove `|| ""`. I think it has more cons than pros.

If you want you can *thoroughly* think & test for edges cases and open a PR.

Anyways: always use +title instead and that should fix the issue. As for titleTemplate use a shared function until the new head management is released.

**Comment by Blankeos** [comment]
Noted on this. Thanks for the replies @brillout!

So `getHeadSetting` does not get the title that was set using `+Head.tsx`. Got it.

Also yeah, I feel like `|| ""` is not a very familiar behavior. If no title was set on this specific page, it probably shouldn't try to clear it. The previous title lingering is a bit more familiar behavior. Then when refreshing that specific page, it would be gone because no title was set for the page.

**Comment by brillout** [comment]
:+1: Looking forward to hear your thoughts!

> The previous title lingering is a bit more familiar behavior

Good point.

**Comment by brillout** [comment]
> Also curious, can I use hooks for checking the pageContext here as well? For instance, changing the title to someone's name for a dynamic profile page.

+title can be a function that receives `pageContext`.

Also, with the upcoming design you'll be able to do this:

```js
import { useConfig } from 'vike-solid/useConfig'

// Inside a Solid component
const config = useConfig()
config({
  title: props.product.name
})

// Also inside Vike hooks such as data()
const config = useConfig()
const data = await fetch(/* ... */)
config({ title: data.product.name })
```

There will be a bunch of settings that can be dynamically set with `useConfig()`.
