### ISSUE TITLE
Export `clientOnly()` at `vike-solid/clientOnly`?

### ISSUE THREAD

**Issue by brillout** [vikejs/vike-solid#89]
It's currently exported at `vike-solid/ClientOnly` (capital `C`) which is a bit misleading.

Btw. if Rollup's code splitting works (I guess so?), then we could squash export paths to the root export `import { clientOnly, useData } from 'vike-solid'`.

**Comment by magne4000** [comment]
> Btw. if Rollup's code splitting works (I guess so?), then we could squash export paths to the root export import { clientOnly, useData } from 'vike-solid'.

I'm not confident in refactoring the build steps too much right now, as it's quite fragile.

**Comment by magne4000** [comment]
Released in `v0.5.0`

**Comment by brillout** [comment]
:+1: Btw. feel free to push commits like https://github.com/vikejs/vike/commit/0437b488ecc05eefb5c5358328ebb7bd11d8bb07 directly to Vike's `main`.
